require('dotenv').config(); const express=require('express'),session=require('express-session'),passport=require('passport'),DiscordStrategy=require('passport-discord').Strategy,axios=require('axios'),path=require('path'); const db=require('./db'),{resolveRank}=require('./config'); const app=express(),PORT=process.env.PORT||3000;
app.set('view engine','ejs'); app.set('views',path.join(__dirname,'..','views')); app.use(express.static(path.join(__dirname,'..','public'))); app.use(express.urlencoded({extended:true})); app.use(session({secret:process.env.SESSION_SECRET||'change-me',resave:false,saveUninitialized:false})); app.use(passport.initialize()); app.use(passport.session()); passport.serializeUser((u,d)=>d(null,u)); passport.deserializeUser((u,d)=>d(null,u));
passport.use(new DiscordStrategy({clientID:process.env.DISCORD_CLIENT_ID,clientSecret:process.env.DISCORD_CLIENT_SECRET,callbackURL:process.env.DISCORD_REDIRECT_URI,scope:['identify']},async(a,r,p,d)=>{try{const m=await axios.get(`https://discord.com/api/v10/guilds/${process.env.DISCORD_GUILD_ID}/members/${p.id}`,{headers:{Authorization:`Bot ${process.env.DISCORD_BOT_TOKEN}`}}); const rank=resolveRank(m.data.roles||[]); if(!rank)return d(null,false); d(null,{id:p.id,username:p.global_name||p.username,rank});}catch(e){d(null,false)}}));
const auth=(q,s,n)=>q.isAuthenticated()?n():s.redirect('/'); const lead=(q,s,n)=>q.user?.rank?.leadership?n():s.status(403).send('Acces doar pentru conducere');
app.get('/',(q,s)=>s.render('index')); app.get('/auth/discord',passport.authenticate('discord')); app.get('/auth/discord/callback',passport.authenticate('discord',{failureRedirect:'/'}),(q,s)=>s.redirect('/dashboard')); app.get('/logout',(q,s)=>q.logout(()=>s.redirect('/')));
app.get('/dashboard',auth,(q,s)=>s.render('dashboard',{user:q.user,reports:db.prepare('SELECT * FROM reports WHERE user_id=? ORDER BY id DESC').all(q.user.id)}));
app.get('/new/:type',auth,(q,s)=>['raport','razie','antrenament'].includes(q.params.type)?s.render('new-report',{user:q.user,type:q.params.type}):s.sendStatus(404));
app.post('/new/:type',auth,(q,s)=>{if(!['raport','razie','antrenament'].includes(q.params.type))return s.sendStatus(404); const {title,description,participants,evidence_url}=q.body; db.prepare('INSERT INTO reports(user_id,username,rank_name,type,title,description,participants,evidence_url) VALUES(?,?,?,?,?,?,?,?)').run(q.user.id,q.user.username,q.user.rank.name,q.params.type,title,description,participants||'',evidence_url||''); s.redirect('/dashboard')});
app.get('/leadership',auth,lead,(q,s)=>s.render('leadership',{user:q.user,reports:db.prepare('SELECT * FROM reports ORDER BY id DESC').all()})); app.post('/leadership/:id/status',auth,lead,(q,s)=>{if(['În așteptare','Aprobat','Respins'].includes(q.body.status))db.prepare('UPDATE reports SET status=? WHERE id=?').run(q.body.status,q.params.id); s.redirect('/leadership')}); app.listen(PORT,()=>console.log(`DIICOT Reports: http://localhost:${PORT}`));
